# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates

version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'daily'

  - package-ecosystem: 'github-actions'
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: '/'
    schedule:
      interval: 'daily'
    groups:
      production-dependencies:
        dependency-type: 'production'
      development-dependencies:
        dependency-type: 'development'

  # Automatically added by streetsidesoftware/public/update-dependabot-github-actions
  - package-ecosystem: github-actions
    directory: /.github/actions/pr
    schedule:
      interval: daily
    commit-message:
      prefix: chore

  # Automatically added by streetsidesoftware/public/update-dependabot-github-actions
  - package-ecosystem: github-actions
    directory: /.github/actions/github-app-token
    schedule:
      interval: daily
    commit-message:
      prefix: chore

  # Automatically added by streetsidesoftware/public/update-dependabot-github-actions
  - package-ecosystem: github-actions
    directory: /.github/actions/is-prerelease
    schedule:
      interval: daily
    commit-message:
      prefix: chore
