# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Spell Checker
email: &email "jason@streetsidesoftware.nl"
name: &name "Jason Dent" # &name is a YAML anchor which can be *referenced later
description: >- # this means to ignore newlines until "baseurl:"
  A Spell Checker for Code!
url: https://streetsidesoftware.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl: "/vscode-spell-checker" # the subpath of your site, e.g. "/blog"
repository: "streetsidesoftware/vscode-spell-checker"
github_username: streetsidesoftware
# twitter_username: jekyllrb
# github_username: jekyll

# Build settings
# theme: jekyll-theme-slate
# theme: minima
remote_theme: pmarsceill/just-the-docs

plugins:
  # - jekyll-feed
  - jekyll-relative-links

# permalink: pretty
permalink: /:categories/:title/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - "**/.cspell.*"
  - "**/.cspell/**"
  - README.md
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

#
# just-the-docs
# See: [Home | Just the Docs](https://pmarsceill.github.io/just-the-docs/)
#

collections:
  - docs
  - drafts
  - release-notes

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

# Aux links for the upper right navigation
aux_links:
  "CSpell":
    - "https://streetsidesoftware.github.io/cspell"
  "GitHub":
    - "https://github.com/streetsidesoftware/vscode-spell-checker"
  "Issues":
    - "https://github.com/streetsidesoftware/vscode-spell-checker/issues"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/streetsidesoftware/vscode-spell-checker" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "blob" # "tree" or "edit" if you want the user to jump into the editor immediately
