$schema: ./node_modules/@cspell/cspell-types/cspell.schema.json
version: "0.2"
language: en-US
flagWords:
  - hte
ignorePaths:
  - .git
  - .gitignore
  - .vscodeignore
  - "*.lock"
  - "*.log"
  - "*.vsix"
  - "*.tsv"
  - "*.svg"
  - "**/__snapshots__/**"
  - "**/server.js"
  - "**/scripts/ts-json-schema-generator.cjs"
  - /samples
  - CHANGELOG.md
  - cspell.json
  - cspell*.{json,yaml}
  - .cspell*.{json,yaml}
  - dist
  - fixtures/workspaces/**
  - languageCodes.ts
  - package-lock.json
  - fixtures/_server/sampleSourceFiles/**
  - packages/_server/sampleSourceFiles/**
  - packages/client/resources/**
  - packages/client/samples/**
  - packages/client/server/**
  - packages/webview-ui/public/assets/**
  - spell-checker-config.schema.json
  - testFixtures
ignoreWords: []
dictionaryDefinitions:
  - name: cities
    path: ./sampleDictionaries/cities.txt
    addWords: false
  - name: cspell-words
    addWords: true
    scope:
      - workspace
    path: ./cspell-words.txt
dictionaries:
  - cities
  - cspell-words
languageSettings:
  - languageId: "*"
    allowCompoundWords: false
overrides:
  - filename: package.json
    ignoreWords:
      - colour
      - canot
useGitignore: true
words:
  - dbaeumer
  - esbenp
