name: create_pr
description: Create A Pull Request That will Trigger Workflows
inputs:
  base:
    description: The Base Ref to apply the diff
    required: false
  body:
    description: Optional body of the PR
    required: false
  commit-message:
    description: Commit Message for the PR
    required: true
  branch:
    description: The Branch to create for the PR
    required: true
  title:
    description: PR title - defaults to commit-message
    required: false
  app_id:
    description: Application ID used to make the PR
    required: true
  app_private_key:
    description: Application Private Key used to sign the PR
    required: true
runs:
  using: "composite"
  steps:
    - name: Has changes
      shell: bash
      run: |
        git --no-pager diff --compact-summary  --exit-code && echo "git_status=clean" >> $GITHUB_ENV || echo "git_status=dirty" >> $GITHUB_ENV
        git --no-pager diff --compact-summary

    - name: Echo git_status
      shell: bash
      run: echo "${{ env.git_status }}"

    - name: Body
      shell: bash
      env:
        git_body: ${{ inputs.body }}
      run: |
        echo "$git_body"

    - uses: ./.github/actions/github-app-token
      if: env.git_status == 'dirty'
      id: generate-token
      with:
        app_id: ${{ inputs.app_id }}
        app_private_key: ${{ inputs.app_private_key }}

    - name: Create Pull Request
      if: env.git_status == 'dirty'
      uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v4
      with:
        commit-message: ${{ inputs.commit-message }}
        branch: ${{ inputs.branch }}
        base: ${{ inputs.base }}
        title: ${{ inputs.title || inputs.commit-message }}
        token: ${{ steps.generate-token.outputs.token }}
        body: ${{ inputs.body }}
        delete-branch: true
