dictionaryDefinitions:
  - name: words16le
    path: ./words16le.dic
    addWords: true
  - name: words16be
    path: ./words/words16be.dic
    addWords: true
dictionaries:
  - words16be
  - words16le
