import type * as vscode from 'vscode';

export type Languages = typeof vscode.languages;

export const languages: Languages = {
    createDiagnosticCollection: jest.fn(),
    getDiagnostics: jest.fn(),
    getLanguages: jest.fn(async () => knownLanguageIDs),
    match: jest.fn(),
    onDidChangeDiagnostics: jest.fn(),
    registerCallHierarchyProvider: jest.fn(),
    registerCodeActionsProvider: jest.fn(),
    registerCodeLensProvider: jest.fn(),
    registerColorProvider: jest.fn(),
    registerCompletionItemProvider: jest.fn(),
    registerDeclarationProvider: jest.fn(),
    registerDefinitionProvider: jest.fn(),
    registerDocumentFormattingEditProvider: jest.fn(),
    registerDocumentHighlightProvider: jest.fn(),
    registerDocumentLinkProvider: jest.fn(),
    registerDocumentRangeFormattingEditProvider: jest.fn(),
    registerDocumentRangeSemanticTokensProvider: jest.fn(),
    registerDocumentSemanticTokensProvider: jest.fn(),
    registerDocumentSymbolProvider: jest.fn(),
    registerEvaluatableExpressionProvider: jest.fn(),
    registerFoldingRangeProvider: jest.fn(),
    registerHoverProvider: jest.fn(),
    registerImplementationProvider: jest.fn(),
    registerInlineValuesProvider: jest.fn(),
    registerLinkedEditingRangeProvider: jest.fn(),
    registerOnTypeFormattingEditProvider: jest.fn(),
    registerReferenceProvider: jest.fn(),
    registerRenameProvider: jest.fn(),
    registerSelectionRangeProvider: jest.fn(),
    registerSignatureHelpProvider: jest.fn(),
    registerTypeDefinitionProvider: jest.fn(),
    registerTypeHierarchyProvider: jest.fn(),
    registerWorkspaceSymbolProvider: jest.fn(),
    setLanguageConfiguration: jest.fn(),
    setTextDocumentLanguage: jest.fn(),
};

// cspell:ignore cuda bibtex dockercompose doctex expl apacheconf hlsl jlweave jqpg juliamarkdown marko mediawiki rsweave scminput terragrunt tfvars
const knownLanguageIDs = [
    'plaintext',
    'code-text-binary',
    'Log',
    'log',
    'scminput',
    'bat',
    'clojure',
    'coffeescript',
    'jsonc',
    'c',
    'cpp',
    'cuda-cpp',
    'csharp',
    'css',
    'dart',
    'dockerfile',
    'ignore',
    'fsharp',
    'git-commit',
    'git-rebase',
    'diff',
    'go',
    'groovy',
    'handlebars',
    'hlsl',
    'html',
    'ini',
    'properties',
    'jupyter',
    'java',
    'javascriptreact',
    'javascript',
    'jsx-tags',
    'json',
    'julia',
    'juliamarkdown',
    'less',
    'lua',
    'makefile',
    'markdown',
    'markdown-math',
    'objective-c',
    'objective-cpp',
    'perl',
    'perl6',
    'php',
    'powershell',
    'jade',
    'python',
    'r',
    'razor',
    'ruby',
    'rust',
    'scss',
    'search-result',
    'shaderlab',
    'shellscript',
    'sql',
    'swift',
    'typescript',
    'typescriptreact',
    'vb',
    'xml',
    'xsl',
    'dockercompose',
    'yaml',
    'tf',
    'tfvars',
    'terragrunt',
    'ada',
    'ali',
    'gpr',
    'zip',
    'toml',
    'scala',
    'jqpg',
    'editorconfig',
    'graphql',
    'vue',
    'mediawiki',
    'tex',
    'doctex',
    'latex',
    'bibtex',
    'bibtex-style',
    'latex-expl3',
    'jlweave',
    'rsweave',
    'cpp_embedded_latex',
    'markdown_latex_combined',
    'svg',
    'jq',
    'haskell',
    'cabal',
    'C2Hs',
    'Hsc2Hs',
    'literate haskell',
    'cfml',
    'FortranFreeForm',
    'fortran_fixed-form',
    'kotlin',
    'kotlinscript',
    'apacheconf',
    'jinja',
    'pip-requirements',
    'raw',
    'marko',
    'avro',
    'hunspell.aff',
    'hunspell.dic',
];
