// cSpell:ignore pycache
import { Connection, TextDocumentUri } from './vscode.workspaceFolders';
import * as vscode from './vscode.workspaceFolders';
import {
    ExcludeFilesGlobMap,
    ExclusionFunction,
    Glob
} from 'cspell';
import * as path from 'path';

import * as CSpell from 'cspell';
import { CSpellUserSettings } from './cspellConfig';
import Uri from 'vscode-uri'

// The settings interface describe the server relevant settings part
export interface Settings {
    cSpell?: CSpellUserSettings;
    search?: {
        exclude?: ExcludeFilesGlobMap;
    };
}

interface VsCodeSettings {
    [key: string]: any;
}

interface ExtSettings {
    uri: string;
    vscodeSettings: Settings;
    settings: CSpellUserSettings;
    fnFileExclusionTest: ExclusionFunction;
}

const defaultExclude: Glob[] = [
    'debug:*',
    'debug:/**',        // Files that are generated while debugging (generally from a .map file)
    'vscode:/**',       // VS Code generated files (settings.json for example)
    'private:/**',
    'markdown:/**',     // The HTML generated by the markdown previewer
    'git-index:/**',    // Ignore files loaded for git indexing
    '**/*.rendered',
    '**/*.*.rendered',
    '__pycache__/**',   // ignore cache files.
];


export class DocumentSettings {
    // Cache per folder settings
    private _settingsByWorkspaceFolder: Promise<Map<string, ExtSettings>> | undefined;
    private readonly settingsByDoc = new Map<string, CSpellUserSettings>();
    private _folders: Promise<vscode.WorkspaceFolder[]> | undefined;
    readonly configsToImport = new Set<string>();
    private _importSettings: CSpellUserSettings | undefined;

    constructor(readonly connection: Connection, readonly defaultSettings: CSpellUserSettings) {}

    async getSettings(document: TextDocumentUri): Promise<CSpellUserSettings> {
        return this.getUriSettings(document.uri);
    };

    async getUriSettings(uri?: string): Promise<CSpellUserSettings> {
        if (!uri) {
            return CSpell.mergeSettings(this.defaultSettings, this.importSettings);
        }
        return this.fetchUriSettings(uri!);
    }

    async isExcluded(uri: string): Promise<boolean> {
        const settingsByWorkspaceFolder = await this.findMatchingFolderSettings(uri);
        const fnExclTests = settingsByWorkspaceFolder.map(s => s.fnFileExclusionTest);
        for (const fn of fnExclTests) {
            if (fn(uri)) {
                return true;
            }
        }
        return false;
    }

    resetSettings() {
        this._settingsByWorkspaceFolder = undefined;
        this.settingsByDoc.clear();
        this._folders = undefined;
        this._importSettings = undefined;
    };

    get folders(): Promise<vscode.WorkspaceFolder[]> {
        if (!this._folders) {
            this._folders = this.fetchFolders();
        }
        return this._folders!;
    }

    private get settingsByWorkspaceFolder() {
        if (!this._settingsByWorkspaceFolder) {
            this._settingsByWorkspaceFolder = this.fetchFolderSettings();
        }
        return this._settingsByWorkspaceFolder!;
    }

    get importSettings() {
        if (!this._importSettings) {
            const importPaths = [...configsToImport.keys()].sort();
            this._importSettings = CSpell.readSettingsFiles(importPaths);
        }
        return this._importSettings!;
    }

    registerConfigurationFile(path: string) {
        configsToImport.add(path);
    }

    private async fetchUriSettings(uri: string): Promise<CSpellUserSettings> {
        const folderSettings = (await this.findMatchingFolderSettings(uri)).map(s => s.settings);
        const spellSettings = CSpell.mergeSettings(this.defaultSettings, this.importSettings, ...folderSettings);
        return spellSettings;
    }

    private async findMatchingFolderSettings(docUri: string): Promise<ExtSettings[]> {
        const settingsByFolder = await this.settingsByWorkspaceFolder;
        return [...settingsByFolder.values()]
            .filter(({uri}) => uri === docUri.slice(0, uri.length))
            .sort((a, b) => a.uri.length - b.uri.length)
            .reverse();
    }

    private async fetchFolders() {
        return await vscode.getWorkspaceFolders(this.connection) || [];
    }

    private async fetchFolderSettings() {
        const folders = await this.fetchFolders();
        const workplaceSettings = readAllWorkspaceFolderSettings(folders);
        const extSettings = workplaceSettings.map(async ([uri, settings]) => {
            const vsCodeSetting: Settings = await vscode.getConfiguration(this.connection, uri);

            const { search = {}, cSpell = {} } = vsCodeSetting;
            const { exclude = {} } = search;

            const mergedSettings = CSpell.mergeSettings(settings, cSpell);
            const { ignorePaths = []} = mergedSettings;
            const globs = defaultExclude.concat(ignorePaths, CSpell.ExclusionHelper.extractGlobsFromExcludeFilesGlobMap(exclude));
            const root = Uri.parse(uri).path;
            const fnFileExclusionTest = CSpell.ExclusionHelper.generateExclusionFunctionForUri(globs, root);

            const ext: ExtSettings = {
                uri,
                vscodeSettings: vsCodeSetting,
                settings: mergedSettings,
                fnFileExclusionTest,
            };
            return ext;
        });
        return new Map<string, ExtSettings>((await Promise.all(extSettings)).map(s => [s.uri, s] as [string, ExtSettings]));
    }
}

const configsToImport = new Set<string>();

function configPathsForRoot(workspaceRoot?: string) {
    return workspaceRoot ? [
        path.join(workspaceRoot, '.vscode', CSpell.defaultSettingsFilename.toLowerCase()),
        path.join(workspaceRoot, '.vscode', CSpell.defaultSettingsFilename),
        path.join(workspaceRoot, CSpell.defaultSettingsFilename.toLowerCase()),
        path.join(workspaceRoot, CSpell.defaultSettingsFilename),
    ] : [];
}

function readAllWorkspaceFolderSettings(workspaceFolders: vscode.WorkspaceFolder[]): [string, CSpellUserSettings][] {
    return workspaceFolders
        .map(folder => folder.uri)
        .map(uri => [uri, configPathsForRoot(uri)] as [string, string[]])
        .map(([uri, paths]) => [uri, CSpell.readSettingsFiles(paths)] as [string, CSpellUserSettings]);
}






