// Generated by typings
// Source: https://raw.githubusercontent.com/typed-typings/npm-mkdirp/198dc9b86004c5a4995ac28ee782c3391fb7ee56/index.d.ts
declare module '~mkdirp/index' {
function mkdirp (path: string, cb: (err: Error, made: string) => any): void;
function mkdirp (path: string, opts: mkdirp.Opts, cb: (err: Error, made: string) => any): void;

module mkdirp {
  export interface Opts {
    fs: any;
    mode: number;
  }

  export function sync (path: string, opts?: mkdirp.Opts): string;
}

export = mkdirp;
}
declare module 'mkdirp/index' {
import main = require('~mkdirp/index');
export = main;
}
declare module 'mkdirp' {
import main = require('~mkdirp/index');
export = main;
}
