import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

    // But you can create a sidebar manually
    docs: [
        {
            type: 'category',
            label: 'Configuration',
            link: {
                type: 'doc',
                id: 'configuration/configuration',
            },
            items: [
                'configuration/code-spell-checker',
                'configuration/files-folders-and-workspaces',
                'configuration/languages-and-dictionaries',
                'configuration/reporting-and-display',
                'configuration/appearance',
                'configuration/cspell',
                'configuration/performance',
                'configuration/advanced',
                'configuration/experimental',
                'configuration/legacy',
            ],
        },
        'commands',
        { type: 'category', label: 'Release Notes', items: ['release-notes/release-notes-v4.0', 'release-notes/release-notes-v2.0'] },
    ],
};

export default sidebars;
