# Publish to VS Code Marketplace when the Release is `released`

name: Auto Publish

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  release:
    types:
      - released


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install
        run: yarn install
      - name: Test
        run: yarn test
      - name: Build Extension .vsix
        run: yarn run package-extension
      - name: Publish VSCE
        run: find ./build -name "*.vsix" | xargs npx vsce publish -p ${{ secrets.VSCE_TOKEN }} --packagePath || echo skipped
      - name: Publish OVSX
        run: find ./build -name "*.vsix" | xargs npx ovsx publish -p ${{ secrets.OVSX_TOKEN }}  || echo skipped
# cspell:ignore vsix xargs OVSX
