name: " 📦 Upload Release Assets"

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Tag of the release to be updated.
        type: string
        required: true
  release:
    types:
      - published
  # push:
  #   # Sequence of patterns matched against refs/tags
  #   tags:
  #     - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_call:
    inputs:
      ref:
        type: string
        required: true

permissions:
  actions: read
  checks: write
  contents: write
  issues: read
  packages: write
  pull-requests: read
  repository-projects: read
  statuses: read

jobs:
  build:
    name: Upload Assets
    env:
      REF: ${{ inputs.ref || github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.REF }}
      - uses: actions/setup-node@v4
        with:
          cache: npm
      - name: Install
        run: npm i
      - name: Build Extension .vsix
        run: npm run package-extension
      - run: zip code-spell-checker build/*

      - name: Upload Assets
        uses: AButler/upload-release-assets@v2.0.2
        with:
          files: "build/code-spell*.vsix"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ env.REF }}
