on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Install # This would actually build your project, using zip for an example artifact
        run: yarn --frozen-lockfile
      - name: Build Extension .vsix
        run: yarn run package-extension
      - run: zip code-spell-checker build/*
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            code-spell-checker.zip

# cspell:ignore vsix softprops
