name: Tag Version for Release

on:
  workflow_dispatch:

jobs:
  tag:
    name: Generate Tags
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - uses: actions/setup-node@v2
        with:
          cache: yarn
      - name: Install
        run: yarn --frozen-lockfile
      - name: Generate Tags
        run: yarn run version-release
      - name: Push tags
        run: |
          git push --follow-tags origin main
